### ISSUE TITLE
 [cbs.com] Failed to parse XML 

### ISSUE THREAD

**Issue by 4cq2** [4cq2/mech#3]
https://www.cbs.com/shows/video/1UAOeMOxr_6Xr7zdPl_V2Qzx4ozLmmhU/

`https://github.com/yt-dlp/yt-dlp/issues/6842`

**Comment by 4cq2** [comment]
fixed:

~~~
> paramount -b 1UAOeMOxr_6Xr7zdPl_V2Qzx4ozLmmhU
GET https://www.paramountplus.com/apps-api/v2.0/androidphone/video/cid/1UAOeMOxr_6Xr7zdPl_V2Qzx4ozLmmhU.json?at=ABAAAAAAAAAAAAAAAAAAAAAA9jDfkJRdbo%2BRDNoMFGetppwEHT95XGHp0Yb%2BIu1zY%2B4%3D
GET http://link.theplatform.com/s/dJ5BDC/media/guid/2198311517/1UAOeMOxr_6Xr7zdPl_V2Qzx4ozLmmhU?assetTypes=Downloadable&formats=MPEG4
GET https://candownloads.cbsaavideo.com/vr/cbsnews/2023/04/05/2190318147900/0416_60MIN_FULL_1_1889822_5192.mp4?hdnea=st=1682167154~exp=1682426384~acl=/vr/cbsnews/2023/04/05/2190318147900/0416_60MIN_FULL_1_1889822_5192.mp4*~hmac=ee3107ea0fbc7486373434f6a566842e5ef37183d52d662b98378b729d881b9c
1.36%   23.07 megabyte   20.93 megabyte/s
~~~

**Comment by 4cq2** [comment]
https://github.com/yt-dlp/yt-dlp/issues/6842

**Comment by 4cq2** [comment]
@JustinJudo

**Comment by LunaLanaLuana** [comment]
I tried to do this and it told me " 'paramount' is not recognized as an internal or external command, "

**Comment by 4cq2** [comment]
that error indicates you are in way, way over your head.

if you want I can guide you through the problem, but I dont provide free support. If you are interested in a quick support session over Discord or similar (15-30 min), I can do that for a fee. If you are interested let me know, otherwise, good luck.

**Comment by LunaLanaLuana** [comment]
What's the cost?

**Comment by 4cq2** [comment]
https://github.com/4cq2/mech#contact
